require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/bedrooms', type: :request do
  # Bedroom. As you add validations to Bedroom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Bedroom.create! valid_attributes
      get bedrooms_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bedroom = Bedroom.create! valid_attributes
      get bedroom_url(bedroom)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bedroom_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      bedroom = Bedroom.create! valid_attributes
      get edit_bedroom_url(bedroom)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Bedroom' do
        expect do
          post bedrooms_url, params: { bedroom: valid_attributes }
        end.to change(Bedroom, :count).by(1)
      end

      it 'redirects to the created bedroom' do
        post bedrooms_url, params: { bedroom: valid_attributes }
        expect(response).to redirect_to(bedroom_url(Bedroom.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Bedroom' do
        expect do
          post bedrooms_url, params: { bedroom: invalid_attributes }
        end.to change(Bedroom, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bedrooms_url, params: { bedroom: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested bedroom' do
        bedroom = Bedroom.create! valid_attributes
        patch bedroom_url(bedroom), params: { bedroom: new_attributes }
        bedroom.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the bedroom' do
        bedroom = Bedroom.create! valid_attributes
        patch bedroom_url(bedroom), params: { bedroom: new_attributes }
        bedroom.reload
        expect(response).to redirect_to(bedroom_url(bedroom))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bedroom = Bedroom.create! valid_attributes
        patch bedroom_url(bedroom), params: { bedroom: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bedroom' do
      bedroom = Bedroom.create! valid_attributes
      expect do
        delete bedroom_url(bedroom)
      end.to change(Bedroom, :count).by(-1)
    end

    it 'redirects to the bedrooms list' do
      bedroom = Bedroom.create! valid_attributes
      delete bedroom_url(bedroom)
      expect(response).to redirect_to(bedrooms_url)
    end
  end
end
