require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/room/types', type: :request do
  # Room::Type. As you add validations to Room::Type, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Room::Type.create! valid_attributes
      get room_types_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      type = Room::Type.create! valid_attributes
      get room_type_url(room_type)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_room_type_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      type = Room::Type.create! valid_attributes
      get edit_room_type_url(room_type)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Room::Type' do
        expect do
          post room_types_url, params: { room_type: valid_attributes }
        end.to change(Room::Type, :count).by(1)
      end

      it 'redirects to the created room_type' do
        post room_types_url, params: { room_type: valid_attributes }
        expect(response).to redirect_to(room_type_url(@room_type))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Room::Type' do
        expect do
          post room_types_url, params: { room_type: invalid_attributes }
        end.to change(Room::Type, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post room_types_url, params: { room_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested room_type' do
        type = Room::Type.create! valid_attributes
        patch room_type_url(room_type), params: { room_type: new_attributes }
        type.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the room_type' do
        type = Room::Type.create! valid_attributes
        patch room_type_url(room_type), params: { room_type: new_attributes }
        type.reload
        expect(response).to redirect_to(room_type_url(type))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        type = Room::Type.create! valid_attributes
        patch room_type_url(room_type), params: { room_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested room_type' do
      type = Room::Type.create! valid_attributes
      expect do
        delete room_type_url(room_type)
      end.to change(Room::Type, :count).by(-1)
    end

    it 'redirects to the room_types list' do
      type = Room::Type.create! valid_attributes
      delete room_type_url(room_type)
      expect(response).to redirect_to(room_types_url)
    end
  end
end
